// Localhost launcher for Guru Manager.
//
// Why this exists: Chrome gates WebNN, WebGPU and Web Workers behind a secure context, and file://
// is not one. http://localhost is. The core app still runs fine by double-clicking the HTML - this
// server exists only so the AI features have a context they're allowed to run in.
//
//   node serve.mjs            then open http://127.0.0.1:8787/
//
// Node stdlib only, no dependencies, no build step.

import {createServer} from 'node:http';
import {createReadStream, statSync} from 'node:fs';
import {readFile} from 'node:fs/promises';
import {extname, normalize, join, sep} from 'node:path';
import {fileURLToPath} from 'node:url';

const ROOT = fileURLToPath(new URL('.', import.meta.url)).replace(/[\\/]$/, '');
// Fixed, never auto-incremented. The port is part of the origin, and a changed origin means a fresh
// IndexedDB + localStorage - i.e. the metadata cache and favorites silently reset. Failing loudly on
// a busy port is much kinder than quietly moving to 8788 and wiping the library index.
const PORT = +(process.env.GURU_PORT || 8787);
const HOST = '127.0.0.1';

const APP = 'Guru Manager ChromeEdge Edition.html';

const MIME = {
    '.html':'text/html; charset=utf-8', '.js':'text/javascript; charset=utf-8',
    '.mjs':'text/javascript; charset=utf-8', '.json':'application/json; charset=utf-8',
    '.css':'text/css; charset=utf-8', '.txt':'text/plain; charset=utf-8',
    // Must be exactly application/wasm or streaming instantiation refuses the module.
    '.wasm':'application/wasm',
    '.onnx':'application/octet-stream', '.bin':'application/octet-stream',
    '.png':'image/png', '.jpg':'image/jpeg', '.jpeg':'image/jpeg', '.webp':'image/webp',
    '.gif':'image/gif', '.svg':'image/svg+xml', '.ico':'image/x-icon'
};

const send = (res, code, body, type='text/plain; charset=utf-8') => {
    res.writeHead(code, {'Content-Type': type, 'Content-Length': Buffer.byteLength(body)});
    res.end(body);
};

createServer(async (req, res) => {
    // COOP+COEP make the page crossOriginIsolated, which is what unlocks SharedArrayBuffer and so
    // multi-threaded WASM. That's a 2-4x win on the CPU fallback path and costs nothing here since
    // every asset is same-origin.
    res.setHeader('Cross-Origin-Opener-Policy', 'same-origin');
    res.setHeader('Cross-Origin-Embedder-Policy', 'require-corp');
    res.setHeader('Cross-Origin-Resource-Policy', 'same-origin');

    let p;
    try{ p = decodeURIComponent(new URL(req.url, `http://${HOST}`).pathname) }
    catch{ return send(res, 400, 'Bad request') }
    if(p === '/' || p === '') p = '/' + APP;

    // Resolve under ROOT and refuse anything that escapes it.
    const abs = normalize(join(ROOT, p));
    if(abs !== ROOT && !abs.startsWith(ROOT + sep)) return send(res, 403, 'Forbidden');

    let st;
    try{ st = statSync(abs) }catch{ return send(res, 404, 'Not found: ' + p) }
    if(st.isDirectory()) return send(res, 403, 'Forbidden');

    const ext = extname(abs).toLowerCase();
    const type = MIME[ext] || 'application/octet-stream';

    // Weights and the ORT runtime are content-addressed by filename and never edited in place, so
    // they cache hard. Everything else must not: manifest.json is REGENERATED by fetch-models.mjs,
    // and serving a stale one is genuinely dangerous - freeDimensionOverrides read from an old
    // manifest build a wrong-shaped graph that fails obscurely (or worse, silently). Only the
    // immutable binary payloads get the long TTL.
    // Be precise about WHAT is immutable. Only third-party runtime bytes under /ai/ort/ and the
    // downloaded weights are content-fixed. Everything else under /ai/ is OUR source -
    // ai-worker.js, ai/src/*.js, manifest.json - and is edited constantly. A broad `/ai/*.js` rule
    // silently pins ai-worker.js for a year, so edits appear to do nothing and you debug ghosts.
    const immutable = p.startsWith('/ai/ort/') || /^\/ai\/models\/.+\.(onnx|bin)$/i.test(p);
    res.setHeader('Cache-Control', immutable
        ? 'public, max-age=31536000, immutable'
        : 'no-store');

    // Range support, so <video> can seek in sample files served from here.
    const range = req.headers.range;
    if(range && /^bytes=\d*-\d*$/.test(range)){
        const [s, e] = range.slice(6).split('-');
        const start = s ? +s : 0, end = e ? Math.min(+e, st.size - 1) : st.size - 1;
        if(start >= st.size || start > end){
            res.writeHead(416, {'Content-Range': `bytes */${st.size}`});
            return res.end();
        }
        res.writeHead(206, {
            'Content-Type': type, 'Content-Length': end - start + 1,
            'Content-Range': `bytes ${start}-${end}/${st.size}`, 'Accept-Ranges': 'bytes'
        });
        return createReadStream(abs, {start, end}).pipe(res);
    }

    res.writeHead(200, {'Content-Type': type, 'Content-Length': st.size, 'Accept-Ranges': 'bytes'});
    if(req.method === 'HEAD') return res.end();
    createReadStream(abs).pipe(res);
})
.on('error', e => {
    if(e.code === 'EADDRINUSE'){
        console.error(`\n  Port ${PORT} is already in use.\n\n` +
            `  Not falling back to another port on purpose: the port is part of the origin, and a\n` +
            `  different origin means a fresh IndexedDB - your metadata cache and favorites would\n` +
            `  silently reset. Free ${PORT}, or set GURU_PORT and use that port from now on.\n`);
        process.exit(1);
    }
    throw e;
})
.listen(PORT, HOST, () => {
    const url = `http://${HOST}:${PORT}/`;
    console.log(`\n  Guru Manager  ->  ${url}\n`);
    console.log(`  Serving ${ROOT}`);
    console.log(`  Bound to ${HOST} only - not reachable from the network.\n`);
    console.log(`  Note: this is a different browser origin than file://, so the metadata cache and`);
    console.log(`  favorites start empty here. That is expected, not a bug.\n`);
});
